spring:
  application:
    name: goormgb
  jackson:
    time-zone: UTC
    data-format: yyyy-MM-dd'T'HH:mm:ss.SSS'Z'

  datasource:
    url: jdbc:postgresql://localhost:5432/goormgb
    username: goormgb
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        jdbc:
          time-zone: UTC

  data:
    redis:
      host: localhost
      port: 6379

jwt:
  secret-key: ${JWT_SECRET_KEY:your-super-secret-key-for-jwt-signing-min-32-chars-long}
  issuer: ${JWT_ISSUER:goormgb-auth-service}
  access-token:
    audience: ${JWT_ACCESS_TOKEN_AUDIENCE:goormgb-api}
    expiration-minutes: ${JWT_ACCESS_TOKEN_EXPIRATION:15}
  refresh-token:
    audience: ${JWT_REFRESH_TOKEN_AUDIENCE:goormgb-auth-service}
    expiration-days: ${JWT_REFRESH_TOKEN_EXPIRATION:7}
