spring:
  application:
    name: goormgb
  jackson:
    time-zone: UTC
    data-format: yyyy-MM-dd'T'HH:mm:ss.SSS'Z'

  datasource:
    url: jdbc:postgresql://localhost:5432/goormgb
    username: goormgb
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        ddl-auto: update
        jdbc:
          time-zone: UTC
      show-sql: true

  data:
    redis:
      host: localhost
      port: 6379
